// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateVhost(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.Vhost>;

export function DeleteVhost(arg1:string):Promise<void>;

export function GetGuessDocumentRoot():Promise<string>;

export function GetVhost(arg1:string):Promise<model.Vhost>;

export function GetVhosts():Promise<Array<model.Vhost>>;

export function RestartApache(arg1:string):Promise<void>;
