// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateVhost(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['VhostController']['CreateVhost'](arg1, arg2, arg3, arg4);
}

export function DeleteVhost(arg1) {
  return window['go']['controller']['VhostController']['DeleteVhost'](arg1);
}

export function GetGuessDocumentRoot() {
  return window['go']['controller']['VhostController']['GetGuessDocumentRoot']();
}

export function GetVhost(arg1) {
  return window['go']['controller']['VhostController']['GetVhost'](arg1);
}

export function GetVhosts() {
  return window['go']['controller']['VhostController']['GetVhosts']();
}

export function RestartApache(arg1) {
  return window['go']['controller']['VhostController']['RestartApache'](arg1);
}
